// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDQ11R1AKS-zFBVPSRg3veRZjj14ttw4Q',
    appId: '1:104202761802:web:3db23d95c09e25778c98b3',
    messagingSenderId: '104202761802',
    projectId: 'online-store-29884',
    authDomain: 'online-store-29884.firebaseapp.com',
    storageBucket: 'online-store-29884.appspot.com',
    measurementId: 'G-L4KGCB0PG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDATpzuBUIiBG00nFPZItQ9TAHX1w0llVc',
    appId: '1:104202761802:android:e421951a441023b28c98b3',
    messagingSenderId: '104202761802',
    projectId: 'online-store-29884',
    storageBucket: 'online-store-29884.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKrg8n28eSnaU5_qb6FPq4NTO5ikgyaok',
    appId: '1:104202761802:ios:763dc7d0531ec5368c98b3',
    messagingSenderId: '104202761802',
    projectId: 'online-store-29884',
    storageBucket: 'online-store-29884.appspot.com',
    iosClientId: '104202761802-uni8h76jrf7ckqubib2f1321sb5n3qt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebaBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKrg8n28eSnaU5_qb6FPq4NTO5ikgyaok',
    appId: '1:104202761802:ios:763dc7d0531ec5368c98b3',
    messagingSenderId: '104202761802',
    projectId: 'online-store-29884',
    storageBucket: 'online-store-29884.appspot.com',
    iosClientId: '104202761802-uni8h76jrf7ckqubib2f1321sb5n3qt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pruebaBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDQ11R1AKS-zFBVPSRg3veRZjj14ttw4Q',
    appId: '1:104202761802:web:87c812fbf7678ed68c98b3',
    messagingSenderId: '104202761802',
    projectId: 'online-store-29884',
    authDomain: 'online-store-29884.firebaseapp.com',
    storageBucket: 'online-store-29884.appspot.com',
    measurementId: 'G-QV38DGZS89',
  );
}
